- name: "Grpc cotea"
  hosts: grpc_cotea_host
  tasks:
    - include_role:
        name: grpc_cotea

- name: "Clouni provider tool install"
  hosts: provider_tool_host
  tasks:
    - include_role:
        name: provider_tool

- name: "Clouni configuration tool install"
  hosts: configuration_tool_host
  tasks:
    - include_role:
        name: configuration_tool