- name: install base packages
  apt:
    name:
      - "git"
      - "python3-pip"
    update_cache: yes
  become: yes

- name: Clone a github repository
  git:
    repo: "{{ configuration_tool_repo }}"
    dest: "/home/{{ user }}/clouni_configuration_tool"
    clone: yes
    update: yes

- name: Clone a github repository
  git:
    repo: "{{ toscaparser_repo }}"
    dest: "/home/{{ user }}/tosca-parser"
    clone: yes
    update: yes

- name: Install requirements
  shell: |
    cd /home/{{ user }}/tosca-parser
    git checkout develop
    python3 -m pip install -r requirements.txt
    python3 setup.py install
    cd /home/{{ user }}/clouni_configuration_tool
    python3 -m pip install -r requirements.txt
    python3 setup.py install
  become: yes

- name: Run server
  shell: /usr/local/bin/clouni-configuration-tool --host 0.0.0.0 -p {{ port }}
  become: yes
    
