version: "3"

services:
  clouni_provider_tool:
    build: provider_tool/
    ports:
      - "50051:50051/tcp"
    network_mode: host

  clouni_configuration_tool:
    build: configuration_tool/
    ports:
      - "50052:50052/tcp"
    network_mode: host

  grpc_cotea:
    volumes:
      - /tmp/clouni:/tmp/clouni
      - /etc/openstack:/tmp/openstack
      - ~/.ssh:/tmp/ssh
      - ~/.aws:/tmp/aws
    command: bash -c -l "cp -r /tmp/openstack /etc/openstack && cp -r /tmp/aws ~/.aws && cp -r /tmp/ssh ~/.ssh && grpc-cotea -p 50151 --host 0.0.0.0"
    build: grpc_cotea/
    ports:
      - "50151:50151/tcp"
    network_mode: host