- name: install base packages
  package:
    name: "python3-pip"
    state: latest
    update_cache: yes
  become: yes

- name: install requirements
  pip:
    name: clouni-provider-tool
    extra_args: -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple
  become: yes

- name: run server
  shell: nohup clouni-provider-tool --host 0.0.0.0 -p {{ port }}
  become: yes
