- name: install base packages
  apt:
    name:
      - "git"
      - "python3-pip"
    update_cache: yes
  become: yes

- name: Install and run
  shell: |
    python3 -m pip install grpcio==1.37.1
    python3 -m pip install grpcio-tools==1.37.1
    python3 -m pip install -i https://test.pypi.org/simple/ grpc-cotea==0.9.5
    python3 -m pip install ansible==2.9.19
    python3 -m pip install openstacksdk==0.46.1
  become: true

- name: Create openstack dir
  shell: mkdir -p /etc/openstack
  become: true

- name: Create openstack dir
  shell: mkdir -p /tmp/clouni/ansible

- name: Copy file
  become: true
  copy:
    src: "/etc/openstack/clouds.yaml"
    dest: "/etc/openstack"

- name: create systemd config for grpc-cotea
  template:
    src: "grpc-cotea.service.j2"
    dest: "/etc/systemd/system/grpc-cotea.service"
  become: yes

- name: refresh daemon
  shell: |
    systemctl daemon-reload
  become: yes

- name: enable and start grpc-cotea service
  service:
    name: grpc-cotea
    state: started
    enabled: yes
  become: yes

    

