- name: install base packages
  apt:
    name:
      - "git"
      - "python3-pip"
    update_cache: yes
  become: yes

- name: Install and run
  shell: |
    python3 -m pip install grpcio==1.37.1
    python3 -m pip install grpcio-tools==1.37.1
    python3 -m pip install -i https://test.pypi.org/simple/ grpc-cotea==0.9.2
    python3 -m pip install ansible==2.9.19
    python3 -m pip install openstacksdk==0.46.0
    export GRPC_ENABLE_FORK_SUPPORT=0
    export GRPC_POLL_STRATEGY=poll
  become: true

- name: Start server
  shell: nohup /usr/local/bin/grpc-cotea --port {{ port }} --host 0.0.0.0 &
  become: true

- name: Create openstack dir
  shell: mkdir -p /etc/openstack
  become: true

- name: Create openstack dir
  shell: mkdir -p /tmp/clouni/ansible

- name: Copy file
  become: true
  copy:
    src: "/etc/openstack/clouds.yaml"
    dest: "/etc/openstack"

    

